export enum DelayCause {
  WEATHER = 'WEATHER',
  MATERIAL_SHORTAGE = 'MATERIAL_SHORTAGE',
  EQUIPMENT_FAILURE = 'EQUIPMENT_FAILURE',
  LABOR_SHORTAGE = 'LABOR_SHORTAGE',
  DESIGN_CHANGE = 'DESIGN_CHANGE',
  OWNER_DIRECTED = 'OWNER_DIRECTED',
  PERMIT_ISSUE = 'PERMIT_ISSUE',
  INSPECTION_HOLD = 'INSPECTION_HOLD',
  UTILITY_CONFLICT = 'UTILITY_CONFLICT',
  SUBCONTRACTOR = 'SUBCONTRACTOR',
  SAFETY_STOP = 'SAFETY_STOP',
  OTHER = 'OTHER',
}
