export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  SUPERINTENDENT = 'SUPERINTENDENT',
  FOREMAN = 'FOREMAN',
  FIELD_WORKER = 'FIELD_WORKER',
  OWNER_REP = 'OWNER_REP',
  SAFETY_OFFICER = 'SAFETY_OFFICER',
}
