export enum VoiceNoteStatus {
  UPLOADING = 'UPLOADING',
  TRANSCRIBING = 'TRANSCRIBING',
  EXTRACTING = 'EXTRACTING',
  REVIEW_READY = 'REVIEW_READY',
  PROCESSED = 'PROCESSED',
  FAILED = 'FAILED',
}
