export enum WeatherCondition {
  CLEAR = 'CLEAR',
  PARTLY_CLOUDY = 'PARTLY_CLOUDY',
  OVERCAST = 'OVERCAST',
  RAIN = 'RAIN',
  HEAVY_RAIN = 'HEAVY_RAIN',
  SNOW = 'SNOW',
  SLEET = 'SLEET',
  FOG = 'FOG',
  WIND = 'WIND',
  THUNDERSTORM = 'THUNDERSTORM',
  EXTREME_HEAT = 'EXTREME_HEAT',
  EXTREME_COLD = 'EXTREME_COLD',
}
